# Parameters for the experiment should be defined here and the contents read by the respective scripts.
deepspectrum:
  extractionNetwork:
    - densenet121
  plotMode:
    - mel
  melBands: 
    - 128
  colourMap:
    - viridis 
  window_size:
  hop_size:

opensmile:
  featureSets:
    - compare16/ComParE_2016.conf 
XBOW:
  csize:
    - 125
    - 250
    - 500
    - 1000
    - 2000
  num_assignments:
    - 10
    - 20
    - 50
svm:
  ci_interval: 0.95
  bootstrap_iterations: 10
fusion:
  to_fuse:
    - auDeep
    - deepspectrum
    - opensmile
    - openXBoW
    - end2you
    - DiFE
